#!/usr/bin/env python3
"""Put the logo's converging tracts in the page banners (replaces the old trajectory curve).

Every page has one decorative <svg class="trajectories"> in its banner. This script rewrites it:
  inner pages (light banner): blue tracts turning MCW green, see-through green arrow  ("A. Logo tracts")
  home page (blue hero):      white tracts turning mint, see-through mint arrow
The SVG stays decorative (aria-hidden). CSS still controls its size, position, and faintness.

Run from the site root:  python3 tools/logo/banner_tracts.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GREEN, LIGHT, MINT = "#007065", "#7eb8e0", "#9fe0cc"
CX, CY = 470, 200                    # convergence point on the 600 x 400 canvas

# Nine tract origins (x, y, node radius), nodes growing toward the front. The banner is short and
# the SVG is cropped top and bottom ("slice"), so nodes stay within the visible band (y about 125-275).
STARTS = [(150, 150, 5.5), (120, 205, 6), (165, 258, 6.5), (230, 132, 7), (235, 200, 8), (270, 268, 8.5),
          (315, 155, 9.5), (335, 245, 10.5), (390, 200, 11.5)]

SVG_RE = re.compile(r'<svg class="trajectories".*?</svg>', re.S)


def banner_svg(on_blue):
    idp = "trh" if on_blue else "trp"
    start, end = ("#ffffff", MINT) if on_blue else (LIGHT, GREEN)
    arrow_color, arrow_op = (MINT, 0.7) if on_blue else (GREEN, 0.5)
    lines = "".join(
        f'<path d="M{x} {y} C{x + (CX - x) * .45:.1f} {y} {CX - (CX - x) * .4:.1f} {CY + (y - CY) * .2:.1f} {CX} {CY}"/>'
        for x, y, _ in STARTS)
    nodes = "".join(f'<circle cx="{x}" cy="{y}" r="{r}" stroke-width="{r * .5:.2f}"/>' for x, y, r in STARTS)
    return (
        f'<svg class="trajectories" viewBox="0 0 600 400" preserveAspectRatio="xMaxYMid slice" aria-hidden="true" focusable="false">\n'
        f'      <!-- Converging tracts from the ForWARD logo. Generated by tools/logo/banner_tracts.py; edit there. -->\n'
        f'      <defs><linearGradient id="{idp}-flow" x1="100" y1="0" x2="{CX}" y2="0" gradientUnits="userSpaceOnUse">'
        f'<stop offset="0" stop-color="{start}"/><stop offset=".5" stop-color="{start}"/><stop offset="1" stop-color="{end}"/></linearGradient></defs>\n'
        f'      <g fill="none" stroke="url(#{idp}-flow)" stroke-width="3.4" stroke-linecap="round">{lines}</g>\n'
        f'      <g opacity="{arrow_op}" fill="none" stroke="{arrow_color}" stroke-width="7.5" stroke-linecap="round" stroke-linejoin="round">'
        f'<path d="M{CX - 4} {CY} L586 {CY}"/><path d="M566 {CY - 20} L590 {CY} L566 {CY + 20}"/></g>\n'
        f'      <g fill="{GREEN}" stroke="#fff">{nodes}</g>\n'
        f'    </svg>')


if __name__ == "__main__":
    for page in sorted(ROOT.glob("*.html")):
        html = page.read_text()
        found = SVG_RE.findall(html)
        if len(found) != 1:
            raise SystemExit(f"{page.name}: expected one banner graphic, found {len(found)}")
        on_blue = page.name == "index.html"          # the home hero is blue; inner banners are light
        page.write_text(SVG_RE.sub(lambda m: banner_svg(on_blue), html))
        print(f"{page.name:18s} {'home (blue)' if on_blue else 'inner (light)'}")
