#!/usr/bin/env python3
"""Build the ForWARD Lab logo files (design "E3, Denser Tracts with green flow").

Writes into assets/img/:
  forward-logo-blue.svg   mark for blue backgrounds (site header and footer)
  forward-logo-white.svg  mark for white or light backgrounds (documents, slides)
  favicon.svg             browser-tab icon: the simplified "E5, clean" version on a blue square
  hero-logo.svg           800x600 slide for the home-page hero rotation: the mark, large, on the site blue

The brain outline and folds come from the MNI152 template (tools/hero_art/brain_paths.json),
mirrored so the frontal lobe faces right ("forward"). Nine tracts start at nodes that grow
toward the front, turn MCW green as they converge, and continue as a see-through arrow.

Run from the site root:  python3 tools/logo/build_logo.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
B = json.load(open(ROOT / "tools/hero_art/brain_paths.json"))
OUT = ROOT / "assets/img"

BLUE, BLUE_DK, GREEN = "#0074c8", "#005a9c", "#007065"
MINT = "#9fe0cc"            # see-through arrow and tract ends on blue (dark green vanishes on blue)
W, H = B["width"], B["height"]
OUTLINE, SULCI = B["outline"], B["sulci"]

# Mark layout on a 160 x 120 canvas; brain scaled by K, mirrored to face right.
K, BX, BY = 0.19, 14, 12
BW, BH = W * K, H * K
FY = BY + BH * 0.42          # where the tracts converge at the frontal lobe
FX = BX + BW - 4
VIEWBOX = "10 8 148 106"     # tight crop around brain, nodes, and arrow

# Nine tract origins (x, y, node radius); nodes grow toward the front.
STARTS = [(30, 40, 2.0), (26, 62, 2.2), (34, 84, 2.4), (50, 28, 2.6), (52, 58, 2.9), (58, 92, 3.1),
          (72, 40, 3.4), (78, 76, 3.7), (94, 58, 4.1)]


def brain_tf():
    return f'transform="translate({BX + W * K:.2f} {BY:.2f}) scale({-K} {K})"'


def tract_paths(stroke, width):
    return "".join(
        f'<path d="M{x} {y} C{x + 30} {y} {FX - 28} {FY + (y - FY) * .25:.1f} {FX} {FY:.1f}" fill="none" '
        f'stroke="{stroke}" stroke-width="{width}" stroke-linecap="round"/>' for x, y, _ in STARTS)


def nodes():
    return "".join(f'<circle cx="{x}" cy="{y}" r="{r}" fill="{GREEN}" stroke="#fff" stroke-width="{r * 0.55:.2f}"/>'
                   for x, y, r in STARTS)


def arrow(on_blue, width=5):
    color, opacity = (MINT, 0.7) if on_blue else (GREEN, 0.5)
    return (f'<g opacity="{opacity}" fill="none" stroke="{color}" stroke-width="{width}" stroke-linecap="round" stroke-linejoin="round">'
            f'<path d="M{FX - 2:.1f} {FY:.1f} L151 {FY:.1f}"/><path d="M142 {FY - 9:.1f} L153 {FY:.1f} L142 {FY + 9:.1f}"/></g>')


def mark(on_blue, idp):
    """E3: outline brain with faded folds, tracts fading to green, see-through arrow, growing nodes."""
    fill = "#1a86d2" if on_blue else "#fff"
    edge = "#fff" if on_blue else BLUE_DK
    folds = ("#c1ddf4", 0.27) if on_blue else ("#4d9bd9", 0.21)
    start = "#fff" if on_blue else "#2f86cf"
    end = MINT if on_blue else GREEN
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="{VIEWBOX}" width="148" height="106" role="img" aria-label="ForWARD Lab">
  <!-- ForWARD Lab mark ({"for blue backgrounds" if on_blue else "for white backgrounds"}). Generated by tools/logo/build_logo.py; edit there. -->
  <defs>
    <clipPath id="{idp}-brain"><path d="{OUTLINE}" {brain_tf()}/></clipPath>
    <linearGradient id="{idp}-flow" x1="20" y1="0" x2="{FX:.1f}" y2="0" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="{start}"/><stop offset=".55" stop-color="{start}"/><stop offset="1" stop-color="{end}"/>
    </linearGradient>
  </defs>
  <path d="{OUTLINE}" {brain_tf()} fill="{fill}" stroke="{edge}" stroke-width="{2.4 / K:.1f}"/>
  <g clip-path="url(#{idp}-brain)" fill="{folds[0]}" opacity="{folds[1]}">{"".join(f'<path d="{p}" {brain_tf()}/>' for p in SULCI)}</g>
  <g clip-path="url(#{idp}-brain)">{tract_paths(f"url(#{idp}-flow)", 2.1)}</g>
  {arrow(on_blue)}
  {nodes()}
</svg>
"""


def favicon():
    """E5, clean: no folds, bolder lines, on a rounded blue square. Reads at 16 to 32 px."""
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="{VIEWBOX}" width="32" height="23">
  <!-- ForWARD Lab browser-tab icon. Generated by tools/logo/build_logo.py; edit there. -->
  <defs><clipPath id="fav-brain"><path d="{OUTLINE}" {brain_tf()}/></clipPath></defs>
  <rect x="10" y="8" width="148" height="106" rx="18" fill="{BLUE}"/>
  <path d="{OUTLINE}" {brain_tf()} fill="#1a86d2" stroke="#fff" stroke-width="{3.4 / K:.1f}"/>
  <g clip-path="url(#fav-brain)">{tract_paths("#fff", 2.8)}</g>
  {arrow(True, width=6.4)}
  {nodes()}
</svg>
"""


def hero_slide():
    """The blue mark centered on an 800x600 slide that matches the hero illustrations' background."""
    inner = mark(True, "hs")
    inner = inner[inner.index("<defs>"):inner.rindex("</svg>")]  # reuse the mark's contents
    vx, vy, vw, vh = map(float, VIEWBOX.split())
    w = 520                                                       # mark width on the slide
    h = w * vh / vw
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600" width="800" height="600">
  <!-- Home-page hero slide: the ForWARD Lab mark on the site blue. Generated by tools/logo/build_logo.py; edit there. -->
  <rect width="800" height="600" fill="{BLUE}"/>
  <svg x="{(800 - w) / 2:.1f}" y="{(600 - h) / 2:.1f}" width="{w}" height="{h:.1f}" viewBox="{VIEWBOX}">
  {inner}
  </svg>
</svg>
"""


if __name__ == "__main__":
    files = {"forward-logo-blue.svg": mark(True, "lb"), "forward-logo-white.svg": mark(False, "lw"), "favicon.svg": favicon(),
             "hero-logo.svg": hero_slide()}
    for name, svg in files.items():
        (OUT / name).write_text(svg)
        print(f"{name:24s} {len(svg) // 1024} KB")
